apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/microservices-dev-434418/image-registry/products-ms
        name: products-ms
        env:
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: file:./dev.db
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
